export const chartData = [
	{
		id: 1,
		title: 'Average Response Time',
		highPriorityColor: '#F05D23',
		borderColor: '#F05D23',
		pointBorderColor: '#F05D23',
		cardTitle: 'Average Response Time',
		responseTimeValue: '+30.4%',
		months: [
			{ value: 10, month: 'Jan' },
			{ value: 20, month: 'Feb' },
			{ value: 10, month: 'Mar' },
			{ value: 30, month: 'Apr' },
			{ value: 49, month: 'May' },
			{ value: 30, month: 'Jun' },
			{ value: 10, month: 'Jul' },
			{ value: 20, month: 'Aug' },
		],
	},
	{
		id: 2,
		title: 'Replies per resolution ',
		highPriorityColor: '#3E68FF',
		borderColor: '#3E68FF',
		pointBorderColor: '#3E68FF',
		cardTitle: 'Average Replies ',
		responseTimeValue: '+25.4%',
		months: [
			{ value: 10, month: 'Jan' },
			{ value: 20, month: 'Feb' },
			{ value: 10, month: 'Mar' },
			{ value: 30, month: 'Apr' },
			{ value: 49, month: 'May' },
			{ value: 30, month: 'Jun' },
			{ value: 10, month: 'Jul' },
			{ value: 20, month: 'Aug' },
		],
	},
	{
		id: 3,
		title: 'First contact resolution rate ',
		highPriorityColor: '#FB6491',
		borderColor: '#FB6491',
		pointBorderColor: '#FB6491',
		cardTitle: 'Average Contact Rate',
		responseTimeValue: '+10%',
		months: [
			{ value: 10, month: 'Jan' },
			{ value: 20, month: 'Feb' },
			{ value: 10, month: 'Mar' },
			{ value: 30, month: 'Apr' },
			{ value: 49, month: 'May' },
			{ value: 30, month: 'Jun' },
			{ value: 10, month: 'Jul' },
			{ value: 20, month: 'Aug' },
		],
	},
	{
		id: 4,
		title: 'Replies per resolution ',
		highPriorityColor: '#07C9E2',
		borderColor: '#07C9E2',
		pointBorderColor: '#07C9E2',
		cardTitle: 'Average Replies ',
		responseTimeValue: '+50%',
		months: [
			{ value: 10, month: 'Jan' },
			{ value: 20, month: 'Feb' },
			{ value: 10, month: 'Mar' },
			{ value: 30, month: 'Apr' },
			{ value: 49, month: 'May' },
			{ value: 30, month: 'Jun' },
			{ value: 10, month: 'Jul' },
			{ value: 20, month: 'Aug' },
		],
	},
];
